TrafficBuddy/config/routes.rb
Rails.application.routes.draw do

  resources :planned_trips

  delete 'planned_trips' => 'planned_trips#destroy_all'

  get 'sessions/new'

  resources :traffic_events
  resources :bookmarked_locations

  post 'bookmarked_locations/create' => 'bookmarked_locations#create'

  resources :users

  root 'application#main'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'update'  => 'traffic_events#parse'

end

TrafficBuddy/app/models/bookmarked_location.rb
class BookmarkedLocation < ActiveRecord::Base
  belongs_to :user
end

TrafficBuddy/app/models/lat_lon.rb
class LatLon < ActiveRecord::Base
  validates :latitude,:longitude,  presence: true
  validates :latitude,:longitude, numericality: true

  belongs_to  :traffic_event
end

TrafficBuddy/app/models/planned_trip.rb
class PlannedTrip < ActiveRecord::Base
  has_many :lat_lons
  belongs_to :user
end

TrafficBuddy/app/models/traffic_event.rb
class TrafficEvent < ActiveRecord::Base
  has_many  :lat_lons
end

TrafficBuddy/app/models/user.rb
class User < ActiveRecord::Base
  has_many :planned_trips

	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :name,  presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 255 }, 
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

  has_many :bookmarked_locations

	# Returns the hash digest of the given string.
	def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end
end

TrafficBuddy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #include SessionsHelper
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper


  def main
    get_api_key
    render 'main/index'
  end

end

TrafficBuddy/app/controllers/lat_lon_controller.rb
class LatLonController < ApplicationController
end

TrafficBuddy/app/controllers/main_controller.rb
class MainController < ApplicationController
end

TrafficBuddy/app/controllers/planned_trips_controller.rb
class PlannedTripsController < ApplicationController

  def index
    @planned_trips = PlannedTrip.all
  end

  def create
    @planned_trip = PlannedTrip.new(params[:planned_trip])
    @planned_trip.user_id = session[:user_id]
    @planned_trip.start_loc = params[:start_location]
    @planned_trip.end_loc = params[:end_location]
    @planned_trip.save
  end

  def destroy
    PlannedTrip.find(params[:id]).destroy
    flash[:success] = "Trip removed"
    redirect_to root_path
  end

  def destroy_all
    @planned_trips = PlannedTrip.where(user_id: session[:user_id])
    @planned_trips.destroy_all
    flash[:success] = "Trips removed"
    redirect_to root_path
  end
end

TrafficBuddy/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

TrafficBuddy/app/controllers/traffic_events_controller.rb
class TrafficEventsController < ApplicationController
  include TrafficEventsHelper, ApplicationHelper

  def index
    get_api_key
    @traffic_events = TrafficEvent.all
  end

  def parse
    parse_traffic
    flash[:notice] = "Traffic events updated"
    redirect_to traffic_events_url
  end
end

TrafficBuddy/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to TrafficBuddy!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

TrafficBuddy/app/helpers/application_helper.rb
module ApplicationHelper
  def get_api_key
    # sets @api_key in all views to either API key set on server or a known Google Maps client key
    # probably a magic """""number""""" but fuck it
    @api_key = ENV['GOOGLE_CLIENT_API_KEY'] || 'AIzaSyA7HCWU3UdcM5WoeuByGBnK4cAOG7V9gJk'
  end
end

TrafficBuddy/app/helpers/bookmarked_locations_helper.rb
module BookmarkedLocationsHelper
end

TrafficBuddy/app/helpers/lat_lon_helper.rb
module LatLonHelper
end

TrafficBuddy/app/helpers/main_helper.rb
module MainHelper
end

TrafficBuddy/app/helpers/planned_trips_helper.rb
module PlannedTripsHelper
end

TrafficBuddy/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

TrafficBuddy/app/helpers/traffic_events_helper.rb
module TrafficEventsHelper
  def parse_traffic
    Feedjira::Feed.add_common_feed_entry_element('georss:line', :as => :location)
    feed = Feedjira::Feed.fetch_and_parse 'http://vanmapp2.vancouver.ca/georss/roadahead_georss.xml'
    @feed = feed.entries
    clear_database
    feed.entries.each do |entry|
      if entry.categories.first != "Upcoming Project"
        tevent = TrafficEvent.new
        tevent.title = entry.title
        tevent.content = entry.content
        parse_latlon(tevent, entry.location)
        tevent.save
      end
    end
  end

  def parse_latlon(tevent, locstr)
    locarray = locstr.split(" ")
    size = locarray.length
    count = 0
    while count < size do
      latlon = LatLon.new
      latlon.traffic_event = tevent
      latlon.latitude = locarray[count]
      latlon.longitude = locarray[count + 1]
      latlon.save

      count += 2
    end
  end

  def clear_database
    TrafficEvent.delete_all
    LatLon.delete_all
  end
end

TrafficBuddy/app/helpers/users_helper.rb
module UsersHelper
end

TrafficBuddy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

  <title>TrafficBuddy</title>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= @api_key %>&libraries=places&sensor=false"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="preloader-main-wrap" id="preloader-overlay">
    <div class="preloader-bg z-depth-2">
        <div class="preloader-wrapper big active">
            <div class="spinner-layer spinner-blue">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div><div class="gap-patch">
                <div class="circle"></div>
            </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
            </div>

            <div class="spinner-layer spinner-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div><div class="gap-patch">
                <div class="circle"></div>
            </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
            </div>

            <div class="spinner-layer spinner-yellow">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div><div class="gap-patch">
                <div class="circle"></div>
            </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
            </div>

            <div class="spinner-layer spinner-green">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div><div class="gap-patch">
                <div class="circle"></div>
            </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
            </div>
        </div>
    </div>
</div>

<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper blue">
          <%= link_to 'TrafficBuddy', root_path, class: 'brand-logo' %>
            <div class="row">
                <ul id="nav" class="col s10 offset-s1">
                    <li><%= link_to 'Traffic Events', controller: 'traffic_events' %></li>
                      <li>
                        <form id="search-field">
                          <div class="input-field" style="width: 500px">
                            <input id="search-query" type="text" placeholder="Search for your destination" required>
                            <label for="search"><i class="mdi-action-search"></i></label>
                          </div>
                        </form>
                      </li>
                    <% if logged_in? %>
                        <li class="no-hover"><%= link_to 'Logout', logout_path, method: "delete", class: 'btn waves-effect waves-light' %></li>
                    <% else %>
                        <li class="no-hover"><%= link_to 'Login', sessions_new_path, class: 'btn waves-effect waves-light' %></li>
                        <li class="no-hover"><%= link_to 'Sign Up', new_user_path, class:'btn waves-effect waves-light no-hover' %></li>
                    <% end %>
                    <% if logged_in? %>
                        <li class="no-hover"><!-- Modal Trigger for favourites --><a class="waves-effect waves-light btn modal-trigger" href="#bookmarked_locations-modal" id="favourites">Favourites</a></li>
                    <% end %>
                    <li class="no-hover"><!-- Modal Trigger for alternative location--><a class="waves-effect waves-light btn modal-trigger" href="#modal2">Location</a></li>
                    <li class="no-hover"><!-- Modal Trigger for trip planning --><a class="waves-effect waves-light btn modal-trigger" href="#trip-modal" id="trip-planner">Plan a Trip</a></li>
                  <%= social_share_button_tag("Check out TrafficBuddy!",
                                                :popup => "true", 
                                                :url => "http://trafficbuddy.com", 
                                                :image => "https://cdn2.iconfinder.com/data/icons/picons-basic-2/57/basic2-185_traffic_cone-128.png", 
                                                desc: "TrafficBuddy, never get stuck in traffic again!", 
                                                via: "TrafficBuddy") %>
                </ul>
            </div>
        </div>
    </nav>
</div>
<a class="button-collapse btn" style="background: none; -webkit-box-shadow: none; box-shadow: none; border: none; color: #aaa; z-index: 9999; position: fixed; top: 0; right: 0; height: 64px; line-height: 64px;" href="#" data-activates="slide-out"><i class="mdi-navigation-menu"></i></a>
<ul id="slide-out" class="s3 side-nav">
 <%= render 'traffic_events/events' %>
</ul>


<!-- Modal Structure for alternative location-->
<div id="modal2" class="modal">
    <div class="modal-content">
        <h4>
            <span class="red-text text-darken-4">Set alternate location</span>
        </h4>
        <div class="row">
            <div class="container">
                <button class="waves-effect waves-light btn modal-action modal-close modal-center" onclick="geolocate()"><i class="mdi-maps-my-location left"></i>Find me automatically</button>
            </div>
        </div>
        <div class="divider"></div>
        <div class="row">
            <form class="col s12" id="location-form">
                <div class="input-field col s12">
                    <input name="location" id="new_location" type="text" class="validate" placeholder="">
                    <label for="new_location">
                        <span class="grey-text text-darken-4">Location</span>
                    </label>
                </div>
            </form>
        </div>
    </div>

    <div class="modal-footer">
        <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close" id="location-submit">Set</a>
        <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Cancel</a>
    </div>
</div>

<!-- Modal Structure for trip planning -->
<div id="trip-modal" class="modal">
    <div class="modal-content">
        <h4>
            <span class="red-text text-darken-4">Plan a Trip</span>
        </h4>
        <% if logged_in? %>
            <div class="row">
                <button class="waves-effect waves-light btn modal-action modal-close" id="select-past-trips">or select a past trip</button>
            </div>
            <div class="divider"></div>
        <% end %>
        <div class="row">
          <form class="col s12" id="trip-form">
            <div class="input-field <% if logged_in? %> col s8 <% end %>">
              <input name="Starting Location" id="start-loc" type="text" class="validate" placeholder="">
              <label id="start-loc-label" for="start-loc">
                <span class="grey-text text-darken-4">Starting Location</span>
              </label>
            </div>
            <% if logged_in? %>
                <div class="col s4" style="height: 61px; position:relative;">
                    <a style="position: absolute; bottom: 0; margin-bottom: 0;" class='dropdown-button btn' data-beloworigin="true" href='#' data-activates='dropdown1'>Select from Favourites</a>

                    <ul id="dropdown1" class="dropdown-content">
                        <% BookmarkedLocation.where(user_id: session[:user_id]).each do |b| %>
                            <li class="start-dropdown" data-start="<%= b.name %>"><a href="#!"><%= b.name %></a></li>
                            <li class="divider"></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="input-field <% if logged_in? %> col s8 <% end %>">
              <input name="Destination Location" id="destination-loc" type="text" class="validate" placeholder="">
              <label id="destination-loc-label" for="destination-loc">
                <span class="grey-text text-darken-4">Destination Location</span>
              </label>
            </div>
            <% if logged_in? %>
                <div class="col s4" style="height: 61px; position:relative;">
                  <a style="position: absolute; bottom: 0; margin-bottom: 0;"  class='dropdown-button btn' data-beloworigin="true" href='#' data-activates='dropdown2'>Select from Favourites</a>

                    <ul id="dropdown2" class="dropdown-content">
                        <% BookmarkedLocation.where(user_id: session[:user_id]).each do |b| %>
                            <li class="end-dropdown" data-end="<%= b.name %>"><a href="#!"><%= b.name %></a></li>
                            <li class="divider"></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <input type="submit" style="display:none;">
          </form>
        </div>
    </div>

    <div class="modal-footer">
      <a href="#" class="waves-effect waves-green btn-flat modal-action" id="trip-submit">Plan</a>
      <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Cancel</a>
    </div>
</div>

<!-- Modal Structure for trip planning -->
<div id="past-trips-modal" class="modal">
  <div class="modal-content">
    <h4>
      <span class="red-text text-darken-4">Select a Past Trip</span>
    </h4>

    <div class="row">
      <button class="waves-effect waves-light btn modal-action modal-close" id="switch-trip-planner">or plan a trip</button>
    </div>
    <div class="divider"></div>
    <table id="planned-trip-table">
    <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Planned on</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>

    <% PlannedTrip.where(user_id: session[:user_id]).each do |planned_trip| %>
        <tr style="cursor: pointer;">
          <td class="planned-trip-row" data-start="<%= planned_trip.start_loc%>" data-end="<%= planned_trip.end_loc%>"> <%= planned_trip.start_loc %> </td>
          <td class="planned-trip-row" data-start="<%= planned_trip.start_loc%>" data-end="<%= planned_trip.end_loc%>"> <%= planned_trip.end_loc %> </td>
          <td class="planned-trip-row" data-start="<%= planned_trip.start_loc%>" data-end="<%= planned_trip.end_loc%>"> <%= planned_trip.created_at %> </td>
          <td class="waves-effect"><%= link_to 'DELETE', planned_trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  </div>

  <div class="modal-footer">
    <%= link_to 'DELETE ALL', planned_trips_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-red red-text text-darken-4 btn-flat modal-action left" %>
    <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Cancel</a>
  </div>
</div>

<!-- Modal Structure for bookmarked locations -->
<div id="bookmarked_locations-modal" class="modal">
  <div class="modal-content">
    <h4>
      <span class="red-text text-darken-4">Bookmarked Locations</span>
    </h4>

    <div class="divider"></div>
    <table id="bookmark-list">
      <thead>
      <tr>
        <th>Location</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>

      <% BookmarkedLocation.where(user_id: session[:user_id]).each do |bookmarked_loc| %>
          <tr style="cursor: pointer;">
            <td class="bookmark-item" data-lat="<%= bookmarked_loc.latitude %>" data-lon="<%= bookmarked_loc.longitude %>"> <%= bookmarked_loc.name %> </td>
            <td class="bookmark-item" data-lat="<%= bookmarked_loc.latitude %>" data-lon="<%= bookmarked_loc.longitude %>"> <%= bookmarked_loc.latitude %> </td>
            <td class="bookmark-item" data-lat="<%= bookmarked_loc.latitude %>" data-lon="<%= bookmarked_loc.longitude %>"> <%= bookmarked_loc.longitude %> </td>
            <td class="waves-effect"><%= link_to 'DELETE', bookmarked_loc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div class="modal-footer">
    <%= link_to 'DELETE ALL', bookmarked_locations_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-red red-text text-darken-4 btn-flat modal-action left" %>
        <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Cancel</a>
  </div>
</div>

<%= yield %>

</body>
</html>

TrafficBuddy/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>